In [2]:
import requests
import pandas as pd
import os 
from dotenv import load_dotenv

In [3]:
found = load_dotenv()
print(found)

api_key = os.getenv("FRED_API_KEY")

if api_key is None:
    raise ValueError("FRED_API_KEY not found.")

True

In [4]:
url = "https://api.stlouisfed.org/fred/series/observations"
params = {"series_id":"CPIAUCSL", "api_key": api_key, "file_type":"json", "observation_start":"2005-01-01"}

response = requests.get(url, params=params, timeout=10)
response.raise_for_status()

data = response.json()
print(type(data), data.keys())

for obs in data["observations"]:
    print(obs["date"], obs["value"])

<class 'dict'> dict_keys(['realtime_start', 'realtime_end', 'observation_start', 'observation_end', 'units', 'output_type', 'file_type', 'order_by', 'sort_order', 'count', 'offset', 'limit', 'observations'])
2005-01-01 191.600
2005-02-01 192.400
2005-03-01 193.100
2005-04-01 193.700
2005-05-01 193.600
2005-06-01 193.700
2005-07-01 194.900
2005-08-01 196.100
2005-09-01 198.800
2005-10-01 199.100
2005-11-01 198.100
2005-12-01 198.100
2006-01-01 199.300
2006-02-01 199.400
2006-03-01 199.700
2006-04-01 200.700
2006-05-01 201.300
2006-06-01 201.800
2006-07-01 202.900
2006-08-01 203.800
2006-09-01 202.800
2006-10-01 201.900
2006-11-01 202.000
2006-12-01 203.100
2007-01-01 203.437
2007-02-01 204.226
2007-03-01 205.288
2007-04-01 205.904
2007-05-01 206.755
2007-06-01 207.234
2007-07-01 207.603
2007-08-01 207.667
2007-09-01 208.547
2007-10-01 209.190
2007-11-01 210.834
2007-12-01 211.445
2008-01-01 212.174
2008-02-01 212.687
2008-03-01 213.448
2008-04-01 213.942
2008-05-01 215.208
2008-06-01 217.463
2008-07-01 219.016
2008-08-01 218.690
2008-09-01 218.877
2008-10-01 216.995
2008-11-01 213.153
2008-12-01 211.398
2009-01-01 211.933
2009-02-01 212.705
2009-03-01 212.495
2009-04-01 212.709
2009-05-01 213.022
2009-06-01 214.790
2009-07-01 214.726
2009-08-01 215.445
2009-09-01 215.861
2009-10-01 216.509
2009-11-01 217.234
2009-12-01 217.347
2010-01-01 217.488
2010-02-01 217.281
2010-03-01 217.353
2010-04-01 217.403
2010-05-01 217.290
2010-06-01 217.199
2010-07-01 217.605
2010-08-01 217.923
2010-09-01 218.275
2010-10-01 219.035
2010-11-01 219.590
2010-12-01 220.472
2011-01-01 221.187
2011-02-01 221.898
2011-03-01 223.046
2011-04-01 224.093
2011-05-01 224.806
2011-06-01 224.806
2011-07-01 225.395
2011-08-01 226.106
2011-09-01 226.597
2011-10-01 226.750
2011-11-01 227.169
2011-12-01 227.223
2012-01-01 227.842
2012-02-01 228.329
2012-03-01 228.807
2012-04-01 229.187
2012-05-01 228.713
2012-06-01 228.524
2012-07-01 228.590
2012-08-01 229.918
2012-09-01 231.015
2012-10-01 231.638
2012-11-01 231.249
2012-12-01 231.221
2013-01-01 231.679
2013-02-01 232.937
2013-03-01 232.282
2013-04-01 231.797
2013-05-01 231.893
2013-06-01 232.445
2013-07-01 232.900
2013-08-01 233.456
2013-09-01 233.544
2013-10-01 233.669
2013-11-01 234.100
2013-12-01 234.719
2014-01-01 235.288
2014-02-01 235.547
2014-03-01 236.028
2014-04-01 236.468
2014-05-01 236.918
2014-06-01 237.231
2014-07-01 237.498
2014-08-01 237.460
2014-09-01 237.477
2014-10-01 237.430
2014-11-01 236.983
2014-12-01 236.252
2015-01-01 234.747
2015-02-01 235.342
2015-03-01 235.976
2015-04-01 236.222
2015-05-01 237.001
2015-06-01 237.657
2015-07-01 238.034
2015-08-01 238.033
2015-09-01 237.498
2015-10-01 237.733
2015-11-01 238.017
2015-12-01 237.761
2016-01-01 237.652
2016-02-01 237.336
2016-03-01 238.080
2016-04-01 238.992
2016-05-01 239.557
2016-06-01 240.222
2016-07-01 240.101
2016-08-01 240.545
2016-09-01 241.176
2016-10-01 241.741
2016-11-01 242.026
2016-12-01 242.637
2017-01-01 243.618
2017-02-01 244.006
2017-03-01 243.892
2017-04-01 244.193
2017-05-01 244.004
2017-06-01 244.163
2017-07-01 244.243
2017-08-01 245.183
2017-09-01 246.435
2017-10-01 246.626
2017-11-01 247.284
2017-12-01 247.805
2018-01-01 248.859
2018-02-01 249.529
2018-03-01 249.577
2018-04-01 250.227
2018-05-01 250.792
2018-06-01 251.018
2018-07-01 251.214
2018-08-01 251.663
2018-09-01 252.182
2018-10-01 252.772
2018-11-01 252.594
2018-12-01 252.767
2019-01-01 252.561
2019-02-01 253.319
2019-03-01 254.277
2019-04-01 255.233
2019-05-01 255.296
2019-06-01 255.213
2019-07-01 255.802
2019-08-01 256.036
2019-09-01 256.430
2019-10-01 257.155
2019-11-01 257.879
2019-12-01 258.630
2020-01-01 259.127
2020-02-01 259.250
2020-03-01 258.076
2020-04-01 256.032
2020-05-01 255.802
2020-06-01 257.042
2020-07-01 258.352
2020-08-01 259.316
2020-09-01 259.997
2020-10-01 260.319
2020-11-01 260.911
2020-12-01 262.045
2021-01-01 262.687
2021-02-01 263.579
2021-03-01 264.961
2021-04-01 266.614
2021-05-01 268.383
2021-06-01 270.654
2021-07-01 271.903
2021-08-01 272.676
2021-09-01 273.910
2021-10-01 276.550
2021-11-01 278.919
2021-12-01 280.845
2022-01-01 282.543
2022-02-01 284.500
2022-03-01 287.674
2022-04-01 288.561
2022-05-01 291.298
2022-06-01 294.957
2022-07-01 294.913
2022-08-01 295.097
2022-09-01 296.349
2022-10-01 298.007
2022-11-01 298.786
2022-12-01 298.832
2023-01-01 300.420
2023-02-01 301.450
2023-03-01 301.821
2023-04-01 302.845
2023-05-01 303.334
2023-06-01 304.014
2023-07-01 304.609
2023-08-01 306.082
2023-09-01 307.276
2023-10-01 307.696
2023-11-01 308.148
2023-12-01 308.741
2024-01-01 309.698
2024-02-01 310.967
2024-03-01 312.345
2024-04-01 313.023
2024-05-01 313.175
2024-06-01 313.044
2024-07-01 313.569
2024-08-01 314.062
2024-09-01 314.732
2024-10-01 315.631
2024-11-01 316.528
2024-12-01 317.604
2025-01-01 318.961
2025-02-01 319.679
2025-03-01 319.785
2025-04-01 320.302
2025-05-01 320.620
2025-06-01 321.435
2025-07-01 322.169
2025-08-01 323.291
2025-09-01 324.245
2025-10-01 .
2025-11-01 325.063
2025-12-01 326.031
2026-01-01 326.588
2026-02-01 327.460
2026-03-01 330.293
2026-04-01 332.407
2026-05-01 333.979
2026-06-01 332.568
2026-07-01 332.813
2026-08-01 334.131
2026-09-01 336.298

In [5]:
print(type(obs["value"]))
print(type(obs["date"]))

<class 'str'>
<class 'str'>

In [6]:
data["observations"][0]

{'realtime_start': '2026-10-22',
 'realtime_end': '2026-10-22',
 'date': '2005-01-01',
 'value': '191.600'}

In [7]:
df = pd.DataFrame(data["observations"])[["realtime_start","realtime_end","date", "value"]]
print(df.shape)
print(df.dtypes)
print(df.tail())

(261, 4)
realtime_start    str
realtime_end      str
date              str
value             str
dtype: object
    realtime_start realtime_end        date    value
256     2026-10-22   2026-10-22  2026-05-01  333.979
257     2026-10-22   2026-10-22  2026-06-01  332.568
258     2026-10-22   2026-10-22  2026-07-01  332.813
259     2026-10-22   2026-10-22  2026-08-01  334.131
260     2026-10-22   2026-10-22  2026-09-01  336.298

In [8]:
df_nulos = df[df["value"] == "."]

nulos = (df["value"]==".").sum()
print(nulos)
print(df_nulos)

1
    realtime_start realtime_end        date value
249     2026-10-22   2026-10-22  2025-10-01     .

In [9]:
FRED_BASE_URL = "https://api.stlouisfed.org/fred/series/observations"

def fetch_fred_series(series_id, start_date, api_key):
    """Fetch observations for a FRED series and return the raw JSON response."""

    params = {"series_id": series_id,
               "api_key": api_key, 
               "file_type": "json", 
               "observation_start": start_date
               }

    response = requests.get(url, params=params, timeout=10)
    response.raise_for_status()

    # Validation of content type
    content_type = response.headers.get("Content-Type","")

    if "application/json" not in content_type:
        raise ValueError(
            f"Expected JSON but received '{content_type}' "
            f"(status {response.status_code}). "
            f"Response starts with: {response.text[:200]}"
        )
    
    return response.json()

In [10]:
#Test with wrong "series_id"
fetch_fred_series("CPIAUCSL", "2005-01-01", api_key)

{'realtime_start': '2026-10-22',
 'realtime_end': '2026-10-22',
 'observation_start': '2005-01-01',
 'observation_end': '9999-12-31',
 'units': 'lin',
 'output_type': 1,
 'file_type': 'json',
 'order_by': 'observation_date',
 'sort_order': 'asc',
 'count': 261,
 'offset': 0,
 'limit': 100000,
 'observations': [{'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-01-01',
   'value': '191.600'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-02-01',
   'value': '192.400'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-03-01',
   'value': '193.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-04-01',
   'value': '193.700'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-05-01',
   'value': '193.600'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-06-01',
   'value': '193.700'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-07-01',
   'value': '194.900'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-08-01',
   'value': '196.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-09-01',
   'value': '198.800'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-10-01',
   'value': '199.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-11-01',
   'value': '198.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2005-12-01',
   'value': '198.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-01-01',
   'value': '199.300'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-02-01',
   'value': '199.400'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-03-01',
   'value': '199.700'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-04-01',
   'value': '200.700'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-05-01',
   'value': '201.300'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-06-01',
   'value': '201.800'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-07-01',
   'value': '202.900'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-08-01',
   'value': '203.800'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-09-01',
   'value': '202.800'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-10-01',
   'value': '201.900'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-11-01',
   'value': '202.000'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2006-12-01',
   'value': '203.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-01-01',
   'value': '203.437'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-02-01',
   'value': '204.226'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-03-01',
   'value': '205.288'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-04-01',
   'value': '205.904'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-05-01',
   'value': '206.755'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-06-01',
   'value': '207.234'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-07-01',
   'value': '207.603'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-08-01',
   'value': '207.667'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-09-01',
   'value': '208.547'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-10-01',
   'value': '209.190'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-11-01',
   'value': '210.834'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2007-12-01',
   'value': '211.445'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-01-01',
   'value': '212.174'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-02-01',
   'value': '212.687'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-03-01',
   'value': '213.448'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-04-01',
   'value': '213.942'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-05-01',
   'value': '215.208'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-06-01',
   'value': '217.463'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-07-01',
   'value': '219.016'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-08-01',
   'value': '218.690'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-09-01',
   'value': '218.877'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-10-01',
   'value': '216.995'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-11-01',
   'value': '213.153'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2008-12-01',
   'value': '211.398'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-01-01',
   'value': '211.933'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-02-01',
   'value': '212.705'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-03-01',
   'value': '212.495'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-04-01',
   'value': '212.709'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-05-01',
   'value': '213.022'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-06-01',
   'value': '214.790'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-07-01',
   'value': '214.726'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-08-01',
   'value': '215.445'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-09-01',
   'value': '215.861'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-10-01',
   'value': '216.509'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-11-01',
   'value': '217.234'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2009-12-01',
   'value': '217.347'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-01-01',
   'value': '217.488'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-02-01',
   'value': '217.281'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-03-01',
   'value': '217.353'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-04-01',
   'value': '217.403'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-05-01',
   'value': '217.290'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-06-01',
   'value': '217.199'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-07-01',
   'value': '217.605'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-08-01',
   'value': '217.923'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-09-01',
   'value': '218.275'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-10-01',
   'value': '219.035'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-11-01',
   'value': '219.590'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2010-12-01',
   'value': '220.472'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-01-01',
   'value': '221.187'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-02-01',
   'value': '221.898'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-03-01',
   'value': '223.046'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-04-01',
   'value': '224.093'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-05-01',
   'value': '224.806'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-06-01',
   'value': '224.806'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-07-01',
   'value': '225.395'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-08-01',
   'value': '226.106'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-09-01',
   'value': '226.597'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-10-01',
   'value': '226.750'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-11-01',
   'value': '227.169'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2011-12-01',
   'value': '227.223'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-01-01',
   'value': '227.842'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-02-01',
   'value': '228.329'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-03-01',
   'value': '228.807'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-04-01',
   'value': '229.187'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-05-01',
   'value': '228.713'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-06-01',
   'value': '228.524'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-07-01',
   'value': '228.590'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-08-01',
   'value': '229.918'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-09-01',
   'value': '231.015'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-10-01',
   'value': '231.638'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-11-01',
   'value': '231.249'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2012-12-01',
   'value': '231.221'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-01-01',
   'value': '231.679'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-02-01',
   'value': '232.937'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-03-01',
   'value': '232.282'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-04-01',
   'value': '231.797'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-05-01',
   'value': '231.893'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-06-01',
   'value': '232.445'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-07-01',
   'value': '232.900'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-08-01',
   'value': '233.456'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-09-01',
   'value': '233.544'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-10-01',
   'value': '233.669'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-11-01',
   'value': '234.100'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2013-12-01',
   'value': '234.719'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-01-01',
   'value': '235.288'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-02-01',
   'value': '235.547'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-03-01',
   'value': '236.028'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-04-01',
   'value': '236.468'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-05-01',
   'value': '236.918'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-06-01',
   'value': '237.231'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-07-01',
   'value': '237.498'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-08-01',
   'value': '237.460'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-09-01',
   'value': '237.477'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-10-01',
   'value': '237.430'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-11-01',
   'value': '236.983'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2014-12-01',
   'value': '236.252'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-01-01',
   'value': '234.747'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-02-01',
   'value': '235.342'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-03-01',
   'value': '235.976'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-04-01',
   'value': '236.222'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-05-01',
   'value': '237.001'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-06-01',
   'value': '237.657'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-07-01',
   'value': '238.034'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-08-01',
   'value': '238.033'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-09-01',
   'value': '237.498'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-10-01',
   'value': '237.733'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-11-01',
   'value': '238.017'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2015-12-01',
   'value': '237.761'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-01-01',
   'value': '237.652'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-02-01',
   'value': '237.336'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-03-01',
   'value': '238.080'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-04-01',
   'value': '238.992'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-05-01',
   'value': '239.557'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-06-01',
   'value': '240.222'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-07-01',
   'value': '240.101'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-08-01',
   'value': '240.545'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-09-01',
   'value': '241.176'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-10-01',
   'value': '241.741'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-11-01',
   'value': '242.026'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2016-12-01',
   'value': '242.637'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-01-01',
   'value': '243.618'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-02-01',
   'value': '244.006'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-03-01',
   'value': '243.892'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-04-01',
   'value': '244.193'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-05-01',
   'value': '244.004'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-06-01',
   'value': '244.163'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-07-01',
   'value': '244.243'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-08-01',
   'value': '245.183'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-09-01',
   'value': '246.435'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-10-01',
   'value': '246.626'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-11-01',
   'value': '247.284'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2017-12-01',
   'value': '247.805'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-01-01',
   'value': '248.859'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-02-01',
   'value': '249.529'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-03-01',
   'value': '249.577'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-04-01',
   'value': '250.227'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-05-01',
   'value': '250.792'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-06-01',
   'value': '251.018'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-07-01',
   'value': '251.214'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-08-01',
   'value': '251.663'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-09-01',
   'value': '252.182'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-10-01',
   'value': '252.772'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-11-01',
   'value': '252.594'},
  {'realtime_start': '2026-10-22',
   'realtime_end': '2026-10-22',
   'date': '2018-12-01',
   'value': '252.767'},

In [11]:
import yfinance as yf 

spy_df_ajust = yf.download("SPY", start="2006-01-01", auto_adjust=True)
print(spy_df_ajust.tail())

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2026-10-19  766.479980  770.460022  765.820007  767.229980  38680100
2026-10-20  769.049988  772.289978  764.250000  765.859985  35048400
2026-10-21  773.090027  774.440002  768.400024  771.169983  31943800
2026-10-22  763.960022  767.710022  761.169983  766.369995  54117100
2026-10-23  759.969971  763.469971  758.679993  759.900024  33377700

In [25]:

spy_df_noajust = yf.download("SPY", start="2006-01-01",multi_level_index=False, auto_adjust=False)
spy_df_noajust.head()

[*********************100%***********************]  1 of 1 completed

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2006-01-03,86.785408,126.699997,127.000000,124.389999,125.190002,73256700
2006-01-04,87.196396,127.300003,127.489998,126.699997,126.860001,51899600
2006-01-05,87.251190,127.379997,127.589996,126.879997,127.150002,47307500
2006-01-06,87.977257,128.440002,128.580002,127.360001,128.020004,62885900
2006-01-09,88.203316,128.770004,129.059998,128.380005,128.419998,43527400

In [13]:
adj_profit = spy_df_ajust.iloc[-1]["Close"] / spy_df_ajust.iloc[0]["Close"] - 1
non_adj_profit = spy_df_noajust.iloc[-1]["Close"] / spy_df_noajust.iloc[0]["Close"] - 1

print(f"Adjusted return: {adj_profit.item():.1%}")   
print(f"Non adjusted return: {non_adj_profit.item():.1%}")

Adjusted return: 775.7%
Non adjusted return: 499.8%

In [23]:
tickers = "SPY, TLT, TIP, GLD, DBC, VNQ"
df = yf.download(tickers, start="2006-01-01", multi_level_index=False,auto_adjust=False)
df.head()

[*********************100%***********************]  6 of 6 completed

Price      Adj Close                                                         \
Ticker           DBC        GLD        SPY        TIP        TLT        VNQ
Date
2006-01-03       NaN  53.119999  86.785416  54.848961  47.121235  25.602392
2006-01-04       NaN  53.299999  87.196426  54.854286  47.234219  25.792011
2006-01-05       NaN  52.340000  87.251183  54.694611  47.177731  25.990040
2006-01-06       NaN  53.720001  87.977242  54.667965  47.090473  26.234449
2006-01-09       NaN  54.599998  88.203300  54.731869  47.121235  26.457771

Price      Close                                     ...        Open  \
Ticker       DBC        GLD         SPY         TIP  ...         SPY
Date                                                 ...
2006-01-03   NaN  53.119999  126.699997  103.040001  ...  125.190002
2006-01-04   NaN  53.299999  127.300003  103.050003  ...  126.860001
2006-01-05   NaN  52.340000  127.379997  102.750000  ...  127.150002
2006-01-06   NaN  53.720001  128.440002  102.699997  ...  128.020004
2006-01-09   NaN  54.599998  128.770004  102.820000  ...  128.419998

Price                                        Volume                     \
Ticker             TIP        TLT        VNQ    DBC      GLD       SPY
Date
2006-01-03  102.690002  91.589996  59.939999    NaN  4606500  73256700
2006-01-04  103.010002  91.540001  61.209999    NaN  5287900  51899600
2006-01-05  102.769997  91.879997  61.240002    NaN  7661800  47307500
2006-01-06  102.720001  91.769997  62.009998    NaN  4629800  62885900
2006-01-09  102.639999  91.699997  62.599998    NaN  5394200  43527400

Price
Ticker         TIP      TLT    VNQ
Date
2006-01-03  257000  1392700  70300
2006-01-04  162400   387600  75000
2006-01-05  169200   453400  31200
2006-01-06  315500  1193700  36000
2006-01-09  288300   413600  49200

[5 rows x 36 columns]

In [15]:
df.shape

(5235, 36)

In [16]:
df.isna().sum()

Price      Ticker
Adj Close  DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
Close      DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
High       DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
Low        DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
Open       DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
Volume     DBC       23
           GLD        0
           SPY        0
           TIP        0
           TLT        0
           VNQ        0
dtype: int64

In [20]:
df['Adj Close']['DBC'].first_valid_index()

Timestamp('2006-02-06 00:00:00')