In [41]:
import duckdb 
from pathlib import Path

In [42]:
con = duckdb.connect()
SPY_PATH = 'C:/Users/ignac/Proyectos/inflation-hedge-analysis/data/raw/prices_SPY.csv'

In [43]:
duckdb.sql("SELECT * FROM read_csv('C:/Users/ignac/Proyectos/inflation-hedge-analysis/data/raw/prices_SPY.csv') LIMIT 5")

┌────────────┬───────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────┐
│    Date    │     Adj Close     │       Close        │        High        │        Low         │        Open        │  Volume  │
│    date    │      double       │       double       │       double       │       double       │       double       │  int64   │
├────────────┼───────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────┤
│ 2005-01-03 │  80.9735336303711 │ 120.30000305175781 │ 121.76000213623047 │  119.9000015258789 │ 121.55999755859375 │ 55748000 │
│ 2005-01-04 │ 79.98406219482422 │ 118.83000183105469 │ 120.54000091552734 │ 118.44000244140625 │ 120.45999908447266 │ 69167600 │
│ 2005-01-05 │  79.4321517944336 │ 118.01000213623047 │             119.25 │              118.0 │ 118.73999786376953 │ 65667300 │
│ 2005-01-06 │ 79.83599090576172 │ 118.61000061035156 │  119.1500015258789 │ 118.26000213623047 │ 118.44000244140625 │ 47814700 │
│ 2005-01-07 │  79.7215576171875 │ 118.44000244140625 │  119.2300033569336 │ 118.12999725341797 │ 118.97000122070312 │ 55847700 │
└────────────┴───────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────┘

In [44]:
duckdb.sql(f"DESCRIBE SELECT * FROM read_csv('{SPY_PATH}')")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ Date        │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ Adj Close   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ Close       │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ High        │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ Low         │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ Open        │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ Volume      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [45]:
DBC_PATH = 'C:/Users/ignac/Proyectos/inflation-hedge-analysis/data/raw/prices_DBC.csv'

duckdb.sql(f"SELECT MAX(DATE) FROM read_csv('{DBC_PATH}')")

┌────────────┐
│ max(DATE)  │
│    date    │
├────────────┤
│ 2026-10-23 │
└────────────┘

In [46]:
duckdb.sql(f"SELECT MIN(DATE) FROM read_csv('{DBC_PATH}')")

┌────────────┐
│ min(DATE)  │
│    date    │
├────────────┤
│ 2006-02-06 │
└────────────┘

In [47]:
duckdb.sql(f"SELECT COUNT(*) FROM read_csv('{DBC_PATH}')")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         5212 │
└──────────────┘

In [48]:
duckdb.sql(f"""
    SELECT COUNT(*) - COUNT("Adj Close") AS null_adj_close
    FROM read_csv('{DBC_PATH}')
""")

┌────────────────┐
│ null_adj_close │
│     int64      │
├────────────────┤
│              0 │
└────────────────┘

In [ ]:
PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"

cpi_path = RAW_DIR / "fred_CPIAUCSL.json"

c:\Users\ignac\Proyectos\inflation-hedge-analysis\notebooks

In [57]:
duckdb.sql(f"DESCRIBE SELECT * FROM read_json('{cpi_path.as_posix()}')").df()

,column_name,column_type,null,key,default,extra
0,realtime_start,DATE,YES,None,None,None
1,realtime_end,DATE,YES,None,None,None
2,observation_start,DATE,YES,None,None,None
3,observation_end,DATE,YES,None,None,None
4,units,VARCHAR,YES,None,None,None
5,output_type,BIGINT,YES,None,None,None
6,file_type,VARCHAR,YES,None,None,None
7,order_by,VARCHAR,YES,None,None,None
8,sort_order,VARCHAR,YES,None,None,None
9,count,BIGINT,YES,None,None,None
10,offset,BIGINT,YES,None,None,None
11,limit,BIGINT,YES,None,None,None
12,observations,"STRUCT(realtime_start DATE, realtime_end DATE,...",YES,None,None,None

In [65]:
duckdb.sql(f" SELECT UNNEST(observations, recursive := true) FROM read_json('{cpi_path.as_posix()}')")

┌────────────────┬──────────────┬────────────┬─────────┐
│ realtime_start │ realtime_end │    date    │  value  │
│      date      │     date     │    date    │ varchar │
├────────────────┼──────────────┼────────────┼─────────┤
│ 2026-10-22     │ 2026-10-22   │ 2005-01-01 │ 191.600 │
│ 2026-10-22     │ 2026-10-22   │ 2005-02-01 │ 192.400 │
│ 2026-10-22     │ 2026-10-22   │ 2005-03-01 │ 193.100 │
│ 2026-10-22     │ 2026-10-22   │ 2005-04-01 │ 193.700 │
│ 2026-10-22     │ 2026-10-22   │ 2005-05-01 │ 193.600 │
│     ·          │     ·        │     ·      │    ·    │
│     ·          │     ·        │     ·      │    ·    │
│     ·          │     ·        │     ·      │    ·    │
│ 2026-10-22     │ 2026-10-22   │ 2026-05-01 │ 333.979 │
│ 2026-10-22     │ 2026-10-22   │ 2026-06-01 │ 332.568 │
│ 2026-10-22     │ 2026-10-22   │ 2026-07-01 │ 332.813 │
│ 2026-10-22     │ 2026-10-22   │ 2026-08-01 │ 334.131 │
│ 2026-10-22     │ 2026-10-22   │ 2026-09-01 │ 336.298 │
└────────────────┴──────────────┴────────────┴─────────┘
  261 rows (10 shown)                        4 columns

In [66]:
duckdb.sql(f"DESCRIBE SELECT UNNEST(observations, recursive := true) FROM read_json('{cpi_path.as_posix()}')")

┌────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│  column_name   │ column_type │  null   │   key   │ default │  extra  │
│    varchar     │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ realtime_start │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ realtime_end   │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ date           │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ value          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [69]:
duckdb.sql(f"""
    SELECT
        obs.date  AS date,
        TRY_CAST(obs.value AS DOUBLE) AS value
    FROM (
        SELECT UNNEST(observations) AS obs
        FROM read_json('{cpi_path.as_posix()}')
    ) AS t
""")

┌────────────┬─────────┐
│    date    │  value  │
│    date    │ double  │
├────────────┼─────────┤
│ 2005-01-01 │   191.6 │
│ 2005-02-01 │   192.4 │
│ 2005-03-01 │   193.1 │
│ 2005-04-01 │   193.7 │
│ 2005-05-01 │   193.6 │
│     ·      │     ·   │
│     ·      │     ·   │
│     ·      │     ·   │
│ 2026-05-01 │ 333.979 │
│ 2026-06-01 │ 332.568 │
│ 2026-07-01 │ 332.813 │
│ 2026-08-01 │ 334.131 │
│ 2026-09-01 │ 336.298 │
└────────────┴─────────┘
  261 rows   2 columns
  (10 shown)

In [ ]:
duckdb.sql(f"""
    SELECT
        COUNT(*)
        COUNT(TRY_CAST(obs.value AS DOUBLE)) AS value
    FROM (
        SELECT UNNEST(observations) AS obs
        FROM read_json('{cpi_path.as_posix()}')
    ) AS t
""")

ParserException: Parser Error: syntax error at or near "("

LINE 4:         COUNT(TRY_CAST(obs.value AS DOUBLE)) AS value
                     ^

In [ ]:
# Casting value to be DOBLE in CPI 

duckdb.sql(f"""
    SELECT
        obs.date, CAST(NULLIF(obs.value, '.') AS DOUBLE) AS value
    FROM (
        SELECT UNNEST(observations) AS obs
        FROM read_json('{cpi_path.as_posix()}')
    ) AS t
""")

┌────────────┬─────────┐
│    date    │  value  │
│    date    │ double  │
├────────────┼─────────┤
│ 2005-01-01 │   191.6 │
│ 2005-02-01 │   192.4 │
│ 2005-03-01 │   193.1 │
│ 2005-04-01 │   193.7 │
│ 2005-05-01 │   193.6 │
│     ·      │     ·   │
│     ·      │     ·   │
│     ·      │     ·   │
│ 2026-05-01 │ 333.979 │
│ 2026-06-01 │ 332.568 │
│ 2026-07-01 │ 332.813 │
│ 2026-08-01 │ 334.131 │
│ 2026-09-01 │ 336.298 │
└────────────┴─────────┘
  261 rows   2 columns
  (10 shown)

In [ ]:
#Extracting series_id from FILENAME in FRED FILES

duckdb.sql(rf"""
    SELECT
        regexp_extract(filename, 'fred_(.+)\.json', 1) AS series_id,
        obs.date                                       AS date,
        CAST(NULLIF(obs.value, '.') AS DOUBLE)         AS value
    FROM (
        SELECT filename, UNNEST(observations) AS obs
        FROM read_json('{RAW_DIR.as_posix()}/fred_*.json', filename = true)
    ) AS t
""")

┌───────────┬────────────┬────────┐
│ series_id │    date    │ value  │
│  varchar  │    date    │ double │
├───────────┼────────────┼────────┤
│ CPIAUCSL  │ 2005-01-01 │  191.6 │
│ CPIAUCSL  │ 2005-02-01 │  192.4 │
│ CPIAUCSL  │ 2005-03-01 │  193.1 │
│ CPIAUCSL  │ 2005-04-01 │  193.7 │
│ CPIAUCSL  │ 2005-05-01 │  193.6 │
│   ·       │     ·      │     ·  │
│   ·       │     ·      │     ·  │
│   ·       │     ·      │     ·  │
│ TB3MS     │ 2026-05-01 │    3.6 │
│ TB3MS     │ 2026-06-01 │   3.66 │
│ TB3MS     │ 2026-07-01 │   3.73 │
│ TB3MS     │ 2026-08-01 │   3.72 │
│ TB3MS     │ 2026-09-01 │   3.94 │
└───────────┴────────────┴────────┘
  522 rows (10 shown)   3 columns

In [ ]:
# Counting how many rows each series has

duckdb.sql(rf"""
    SELECT
        regexp_extract(filename, 'fred_(.+)\.json', 1) AS series_id,
        COUNT(*)
    FROM (
        SELECT filename, UNNEST(observations) AS obs
        FROM read_json('{RAW_DIR.as_posix()}/fred_*.json', filename = true)
    ) AS t
    GROUP BY series_id
""")

┌───────────┬──────────────┐
│ series_id │ count_star() │
│  varchar  │    int64     │
├───────────┼──────────────┤
│ TB3MS     │          261 │
│ CPIAUCSL  │          261 │
└───────────┴──────────────┘

In [ ]:
#Extracting ticker_id from all the csvs

duckdb.sql(rf"""
    SELECT
        Date as date,
        regexp_extract(filename, 'prices_(.+)\.csv', 1) AS ticker,
        "Adj Close" AS adj_close,
        Close       AS close,
        High        AS high,
        Low         AS low,
        Open        AS open,
        Volume      AS volume
    FROM read_csv('{RAW_DIR.as_posix()}/prices_*.csv', filename = true)
""")

┌────────────┬─────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────┐
│    date    │ ticker  │     adj_close      │       close        │        high        │        low         │        open        │ volume  │
│    date    │ varchar │       double       │       double       │       double       │       double       │       double       │  int64  │
├────────────┼─────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────┤
│ 2006-02-06 │ DBC     │ 19.185100555419922 │ 24.200000762939453 │  24.65999984741211 │ 24.100000381469727 │ 24.549999237060547 │  771500 │
│ 2006-02-07 │ DBC     │ 18.630157470703125 │               23.5 │ 24.200000762939453 │ 23.450000762939453 │ 24.049999237060547 │  674400 │
│ 2006-02-08 │ DBC     │ 18.550880432128906 │ 23.399999618530273 │ 23.670000076293945 │ 23.329999923706055 │ 23.489999771118164 │  335400 │
│ 2006-02-09 │ DBC     │  18.72528839111328 │   23.6200008392334 │  23.81999969482422 │ 23.510000228881836 │ 23.559999465942383 │  705900 │
│ 2006-02-10 │ DBC     │   18.3843994140625 │ 23.190000534057617 │ 23.690000534057617 │ 23.100000381469727 │ 23.649999618530273 │  276700 │
│     ·      │  ·      │           ·        │          ·         │                ·   │          ·         │          ·         │     ·   │
│     ·      │  ·      │           ·        │          ·         │                ·   │          ·         │          ·         │     ·   │
│     ·      │  ·      │           ·        │          ·         │                ·   │          ·         │          ·         │     ·   │
│ 2024-01-04 │ GLD     │ 189.32000732421875 │ 189.32000732421875 │             189.75 │ 188.69000244140625 │  189.0800018310547 │ 4416700 │
│ 2024-01-05 │ GLD     │ 189.35000610351562 │ 189.35000610351562 │ 191.25999450683594 │  189.0800018310547 │ 189.67999267578125 │ 7481900 │
│ 2024-01-08 │ GLD     │  187.8699951171875 │  187.8699951171875 │ 188.74000549316406 │ 187.11000061035156 │  187.2100067138672 │ 6215000 │
│ 2024-01-09 │ GLD     │ 187.92999267578125 │ 187.92999267578125 │ 188.77999877929688 │ 187.72999572753906 │ 188.67999267578125 │ 4437300 │
│ 2024-01-10 │ GLD     │              187.5 │              187.5 │ 188.44000244140625 │  187.2100067138672 │ 188.13999938964844 │ 4504700 │
└────────────┴─────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────────┘
  ? rows (>9999 rows, 10 shown)                                                                                                 8 columns

In [ ]:
#Total Rows

duckdb.sql(rf"""
    SELECT
        COUNT(regexp_extract(filename, 'prices_(.+)\.csv', 1)) AS TICKER
    FROM read_csv('{RAW_DIR.as_posix()}/prices_*.csv', filename = true)
""")

┌────────┐
│ TICKER │
│ int64  │
├────────┤
│  32647 │
└────────┘

In [ ]:
# How many rows per ticker

duckdb.sql(rf"""
    SELECT
        COUNT(*),
        regexp_extract(filename, 'prices_(.+)\.csv', 1) AS ticker
    FROM read_csv('{RAW_DIR.as_posix()}/prices_*.csv', filename = true)
    GROUP BY ticker
""")

┌──────────────┬─────────┐
│ count_star() │ ticker  │
│    int64     │ varchar │
├──────────────┼─────────┤
│         5487 │ SPY     │
│         5487 │ TIP     │
│         5487 │ TLT     │
│         5487 │ GLD     │
│         5212 │ DBC     │
│         5487 │ VNQ     │
└──────────────┴─────────┘

In [96]:
#View that will be utiliced for checking nulls

duckdb.sql(rf"""
    CREATE OR REPLACE VIEW stg_prices_preview AS
    SELECT
        Date                                            AS date,
        regexp_extract(filename, 'prices_(.+)\.csv', 1) AS ticker,
        "Adj Close"                                     AS adj_close,
        Close                                           AS close,
        High                                            AS high,
        Low                                             AS low,
        Open                                            AS open,
        Volume                                          AS volume
    FROM read_csv('{RAW_DIR.as_posix()}/prices_*.csv', filename = true)
""")

┌────────┐
│ Count  │
│ int64  │
└────────┘
  0 rows

In [97]:
duckdb.sql("SELECT COUNT(*) AS total_rows FROM stg_prices_preview")

┌────────────┐
│ total_rows │
│   int64    │
├────────────┤
│      32647 │
└────────────┘

In [98]:
duckdb.sql("""
    SELECT
        ticker,
        COUNT(*),
        MIN(DATE) as first_date, 
        MAX(DATE) as last_date,
    FROM stg_prices_preview
    GROUP BY ticker    
    ORDER BY ticker
""")

┌─────────┬──────────────┬────────────┬────────────┐
│ ticker  │ count_star() │ first_date │ last_date  │
│ varchar │    int64     │    date    │    date    │
├─────────┼──────────────┼────────────┼────────────┤
│ DBC     │         5212 │ 2006-02-06 │ 2026-10-23 │
│ GLD     │         5487 │ 2005-01-03 │ 2026-10-23 │
│ SPY     │         5487 │ 2005-01-03 │ 2026-10-23 │
│ TIP     │         5487 │ 2005-01-03 │ 2026-10-23 │
│ TLT     │         5487 │ 2005-01-03 │ 2026-10-23 │
│ VNQ     │         5487 │ 2005-01-03 │ 2026-10-23 │
└─────────┴──────────────┴────────────┴────────────┘

In [100]:
duckdb.sql("""
    SELECT 
        date,
        ticker,
        count(*) as n
    FROM stg_prices_preview
    GROUP BY date, ticker 
    HAVING COUNT(*) > 1 
""")

┌──────┬─────────┬───────┐
│ date │ ticker  │   n   │
│ date │ varchar │ int64 │
└──────┴─────────┴───────┘
          0 rows